### ISSUE TITLE
Phyloseq & DESeq2: phyloseq_to_deseq2 reference issues

### ISSUE THREAD

**Issue by nfellaby** [joey711/phyloseq#667] opened 2016-09-14 15:21 UTC
Hi Joey,

First of, great package, absolutely fantastic, not only has it allowed me to explore my data to a new  depth (relative to QIIME) but it's also taught me the errors of rarefying my OTUS.

Which brings me neatly onto my problem.

As far as I know there is nothing abnormal about my dataset, it's all been used/generate from via QIIME.

I created my own phyloseq object using your tutorial:

> biom_file = "../MiSeq/OTU_table.biom"
> map_file= "./Alpha_metadata.tsv"
> 
> biom<-import_biom(biom_file, parseFunction = parse_taxonomy_default)
> bmsd = import_qiime_sample_data(map_file)
> all = merge_phyloseq(biom, bmsd)

The phyloseq object 'All' looks like this:

> phyloseq-class experiment-level object
> otu_table()   OTU Table:         [ 87 taxa and 798 samples ]
> sample_data() Sample Data:       [ 798 samples by 22 sample variables ]
> tax_table()   Taxonomy Table:    [ 87 taxa by 7 taxonomic ranks ]

The information I want to compare are located in the column "Description", and consist of only 2 variables, "control" and "Confirmed".  So I attempted to convert the phyloseq object into a DESeq2 object.

> diagdds = phyloseq_to_deseq2(all, ~Description)

However, this leaves me with the following error:

> converting counts to integer mode
> it appears that the last variable in the design formula, 'Description',
>   has a factor level, 'control', which is not the reference level. we recommend
>   to use factor(...,levels=...) or relevel() to set this as the reference level
>   before proceeding. for more information, please see the 'Note on factor levels'
>   in vignette('DESeq2').

I have made crude attempts at addressing this based on the output, i.e.

> all$Description<-relevel(all$Description, ref="Control")
> all$Description<-relevel(all$Description, ref="Control", "Confirmed")
 

Leaving me with the next error, and me feeling way too deep into R to understand what's actually happening..

> Error in all$Description : $ operator not defined for this S4 class

Apologies if this has been posted previously, I have scoured your github pages, and good for about a week for a solution, but unfortunately nothing appears to help me resolve this problem.

Regardless, thank you ever so much for all the time you have already invested into this marvellous piece of software. Sincerely,

nicholas.

**Comment by joey711** [comment] 2016-09-14 23:07
Hi @nfellaby 

Thanks, glad you seem to be getting a lot out of phyloseq. 

That particular error message is coming from the core of R, because your data object `all` has no `$` method, which is an operator reserved mostly for accessing or assigning to a list or data.frame, which your data is not (it is a "phyloseq" object). However, the `sample_data` component of the phyloseq object inherits from data.frame, hence `$` will appear in my recommended approach below.

I'm steadily consolidating the doc for phyloseq so that it is easier to find. Your question should probably be included in the FAQ, but it is also documented in the "[phyloseq basics](https://joey711.github.io/phyloseq/merge.html#merge_samples)" vignette, which comes up in a search of `"phyloseq add variable"`. For convenience, here is the reproducible code chunk shown in that vignette.

```r
library("phyloseq")
data(GlobalPatterns)
GP = GlobalPatterns
GP = prune_taxa(taxa_sums(GlobalPatterns) > 0, GlobalPatterns)
humantypes = c("Feces", "Mock", "Skin", "Tongue")
sample_data(GP)$human <- get_variable(GP, "SampleType") %in% humantypes
```

The critical line is the last one, which from your example would be:

```r
sample_data(all)$Description <- relevel(get_variable(all, "Description"), ref="Control")
```

This assumes that `get_variable(all, "Description")` returns a factor. If not, here is the solution.

```r

sample_data(all)$Description <- relevel(as.factor(get_variable(all, "Description")), ref="Control")
```

That should do it. I will close for now, but feel free to post more, especially if this missed the mark.

Cheers

joey

**Closed by joey711** 2016-09-14 23:07 UTC

**Comment by fabipc** [comment] 2018-08-22 21:39
Hi Joey711, 


I am having the same problem as above, but I am confused on the coding, especially on the last line, as when I run It I get an error. When I run it as your example, all it tells me is T, T, T,  but when I change the last line to your suggestion, I get the following error. 

PS = physeq.b
PS = prune_taxa(taxa_sums(physeq.b) > 0, physeq.b)
FY = c("2006", "2012", "2014", "2015")
sample_data(PS)$FireYear <-  relevel(as.factor(get_variable(PS, "FireYear")), ref="2006")


Can you please help me out, thanks

**sample_data(PS)$FireYear <-  relevel(as.factor(get_variable(PS, "FY")), ref="2006")
Error in `[.data.frame`(as(sample_data(physeq), "data.frame"), , varName) : 
  undefined columns selected**
