### ISSUE TITLE
tax_glom returns with confusing row names

### ISSUE THREAD

**Issue by antagomir** [joey711/phyloseq#477] opened 2015-05-16 20:50 UTC
When agglomerating OTUs into higher level:

data(GlobalPatterns) 
GlobalPatterns2 <- tax_glom(GlobalPatterns, "Phylum")

The returning phyloseq object has 66 taxa. This is correct since there are 66 Phyla. 

The OTU table rownames are however named by the OTU IDs:
rownames(otu_table(GlobalPatterns2)@.Data) 

This is confusing since the agglomerated OTU table has only 66 rows, and these apparently correspond to the read counts of the corresponding Phyla, and not to the original OTUs. Therefore the rownames of the otu_table are misleading. 

I propose that the rownames would be named by the corresponding higher-level taxa.

**Comment by audy** [comment] 2015-05-17 21:59
> The OTU table rownames are however named by the OTU IDs:

They're named by the taxonomy IDs.

> I propose that the rownames would be named by the corresponding higher-level taxa.

I'm not sure why you would want to do this. Don't you want the row.names to correspond to a taxonomic description in the taxonomy table?

Maybe a better thing to do would be to rename `otu_table` to `abundances_table` since it may not necessarily hold OTUs.

**Comment by antagomir** [comment] 2015-05-17 22:45
The otu_table generated by 'tax_glom(GlobalPatterns, "Phylum")' contains exactly 66 rows. These rows correspond to the sum of read counts over all taxa (ie. taxonomy IDs) for each Phylum (there are 66 Phyla in total). Each row therefore corresponds to a sum  over multiple taxonomy IDs, therefore it is misleading to name a row with a single taxonomy ID when the row corresponds to a sum over many taxonomy IDs (ie. a higher level taxonomic group). Since each row does correspond to a specific higher-level taxonomic group, it would be appropriate and practical to name the rows according to those groups. Or not name them at all since the currently used taxonomy IDs are misleading.

For instance agglomeration to Phylum level :
GlobalPatterns2 <- tax_glom(GlobalPatterns, "Phylum")
a <- otu_table(GlobalPatterns2)[1,]

Same by manually calculating sum of read counts for the Phylum "Crenarchaeota":  
b <- colSums(otu_table(GlobalPatterns)[rownames(subset(as.data.frame(tax_table(GlobalPatterns)), Phylum == "Crenarchaeota")),])

This shows that agglomeration corresponds to the total read counts of the specified Phylum:
all(a == b) # TRUE

Since the rows of the otu_table(GlobalPatterns2) correspond to the total read counts per Phyla, I can't see why these rows should be named by taxonomy IDs. This is clearly misleading: the taxonomy IDs have different counts, given in the original otu_table(GlobalPatterns).

Changing the name otu_table to abundance_table could clarify the semantics and I support that. But that change would not solve the current issue of misleading row names in the agglomerated table.

**Comment by audy** [comment] 2015-05-18 01:27
> it is misleading to name a row with a single taxonomy ID when the row corresponds to a sum over many taxonomy IDs 

This is incorrect. Taxonomy IDs do map to higher-level taxonomies. NCBI has IDs for higher level taxa. So does GreenGenes. I believe Phyloseq uses these. Take GreenGenes ID `549322` for example. The taxonomy for this is only defined to the Class rank.

> This is clearly misleading: the taxonomy IDs have different counts

I agree that this might be a mildly irritating inconsistency. There are multiple (technical) reasons for this.

The first is reason is due to R's interal data structures. Phyloseq uses dataframes internally to represent OTU tables. R's dataframes have a single index. There exist implementations of multiple-index data-frames in other languages (the Pandas library in Python comes to mind) which would allow you to get the occurrence counts for ALL OTUs given a "higher-rank" taxonomy ID. An implementation of this in Phyloseq might be interesting as it would remove the need to agglomerate in the first place (one could get the "Phylum" OTU table just by selecting only the Phylum OTU IDs). I am not aware of a similar data structure in R that would allow for this.

The second reason has to do with how sequence reads are classified during OTU picking. Some OTU picking algorithms attempt to classify reads to the lowest possible rank but stop when confidence drops. The RDP classifier and Kraken metagenomic read classifiers both do this. Therefore, these higher level taxonomy IDs have a real meaning. They represent reads that could not be classified any more specifically.

Is there a specific problem that this inconsistency creates? Do you have any suggestions for a better implementation?

**Comment by joey711** [comment] 2015-05-18 17:45
"Phyloseq uses dataframes internally to represent OTU tables"

This is false. OTU tables and taxonomy tables are represented with matrices, sample covariates are stored with `data.frame`, and the tree is a special object all by itself, but basically a list in which one of the elements has a highly structured two-column list.

"I am not aware of a similar data structure in R that would allow for this."

The `data.table` class supports multiple-indexing. And it is crazy fast and memory efficient. If I were to massively re-write the phyloseq data infrastructure, it would be with `data.table`. 

One problem I see is that the "internal node" IDs is not going to be universally available for all user datasets (or user opinions about taxonomy O:-) ). So the first hurdle would be to come up with a way of doing this that still fully supports datasets that, for instance, don't even have a taxonomic annotation, or don't want/need/agree-with internal-node IDs.

I like where this is going, and other folks have been expressing interest in "beefing up" the phyloseq data infrastructure to better support other covariate data, both on the samples, on the features, and so on. Bioconductor already has a "stack" of classes for this that have some years of effort from the microarray and RNA-Seq disciplines, and my first thought is simply to migrate over to these tools similar to what the "metagenomeSeq" package did... but still including a tree class for phylogeny-related stuff like tree plotting, UniFrac, DPCoA, etc.

Thoughts?

**Comment by joey711** [comment] 2015-05-18 18:00
Also, my last comment is a tangent from the OP's issue. Sorry. 

Here is the short answer:
There must be feature IDs for cross-referencing between core data types in a phyloseq object. The core agglomeration methods (for features it is called `merge_taxa`) have somewhat arbitrary heuristics for picking one from the set of IDs being agglomerated to use as the representative ID that is retained for cross-referencing. My mind is foggy and when, but in some cases the feature with largest sum across the abundance matrix is selected, and in others it might just be the first in the set (so really, really arbitrary). In any case, this approach has some utility for users because many agglomeration needs are essentially further revisions of their original OTU-clustering, a kind of phylogenetic coarse-graining.

I agree with Austin's point that a better data-structure could improve this so that a second agglomerated copy of the phyloseq instance would not be needed. This has some advantages in preventing error/bug propagation in a user's script, and other reproducible research advantages. 

I will close this issue for now, as the current behavior is expected and needed. Matrix row names are not always going to accept taxonomic entries, which can be any arbitrary string or missing. In the stated example, the "Phylum" rank is still preserved in the taxonomyTable, so the information has not been lost, is in the proper place for downstream phyloseq methods, and is the intended/needed separation between index-ID and taxonomic "data".

Let's continue the data infrastructure discussion in the appropriate thread, post, PR.

Cheers

joey

**Closed by joey711** 2015-05-18 18:00 UTC
