### ISSUE TITLE
psmelt returns empty df

### ISSUE THREAD

**Issue by DeniRibicic** [joey711/phyloseq#1035] opened 2018-11-15 09:28 UTC
Hi folks,

I am having an issue when melting a specific `phyloseq` object, `df` returns empty without any error:

>  df
 [1] OTU                  Sample               Abundance            X.SampleID           BarcodeSequence      LinkerPrimerSequence SampleNumbers        SampleNumbersII     
 [9] Location             SamplingPosition     Replicate            replicate_alt        TimePoint            Date                 Description          Kingdom             
[17] Phylum               Class                Order                Family               Genus                Species             
<0 rows> (or 0-length row.names)

The trouble is only with this specific object. However I am not able to pinpoint what seems to be the problem. 

When I create the `phyloseq` object I can see that there is data in it:

> phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 8248 taxa and 60 samples ]
sample_data() Sample Data:       [ 60 samples by 12 sample variables ]
tax_table()   Taxonomy Table:    [ 8248 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 8248 tips and 8228 internal nodes ]
refseq()      DNAStringSet:      [ 8248 reference sequences ]

Also, checking specific parts of the object returns loaded df :

> head(sample_data(Q2))
Sample Data:        [6 samples by 12 sample variables]:
     X.SampleID BarcodeSequence LinkerPrimerSequence SampleNumbers SampleNumbersII Location SamplingPosition Replicate replicate_alt TimePoint       Date Description
100i       100i              NA                   NA          100I             100        C               S1         A            p1       t17 02.07.2018            
103i       103i              NA                   NA          103I             103        C               S2         A            p1       t17 02.07.2018            
106i       106i              NA                   NA          106I             106        C                B         A            p1       t17 02.07.2018            
109i       109i              NA                   NA          109I             109        D               K1         A            p1       t16 18.06.2018            
10i         10i              NA                   NA           10I              10        B               S1         A            p1       t16 18.06.2018            
112i       112i              NA                   NA          112I             112        D               K2         A            p1       t16 18.06.2018            

or

> head(tax_table(Q2))
Taxonomy Table:     [6 taxa by 7 taxonomic ranks]:
                                 Kingdom         Phylum Class Order Family Genus Species
120b33d28e807a2d9b66fab4e362792c "Unassigned"    NA     NA    NA    NA     NA    NA     
40c2a38772c5844b266ced7affcc5823 "D_0__Bacteria" NA     NA    NA    NA     NA    NA     
91e0412d96074afa0ff8f51ae6433c51 "Unassigned"    NA     NA    NA    NA     NA    NA     
8c691144d0091ef9eed7a9675242e0e8 "Unassigned"    NA     NA    NA    NA     NA    NA     
fe1249118078655daaae50ec71675bfc "Unassigned"    NA     NA    NA    NA     NA    NA     
b87b19ac7c95a095cae2f798e53aef4f "Unassigned"    NA     NA    NA    NA     NA    NA     

and

> head(otu_table(Q2))
OTU Table:          [6 taxa and 60 samples]
                     taxa are rows
                                 100i 103i 106i 109i 10i 112i        115i 118i 121i 124i 127i 130i 133i 136i 139i 13i 142i 145i 148i 151i 154i 157i 160i        163i 166i
120b33d28e807a2d9b66fab4e362792c    0    0    0    0   0    0 0.000000000    0    0    0    0    0    0    0    0   0    0    0    0    0    0    0    0 0.000000000    0
40c2a38772c5844b266ced7affcc5823    0    0    0    0   0    0 0.000000000    0    0    0    0    0    0    0    0   0    0    0    0    0    0    0    0 0.006284828    0
91e0412d96074afa0ff8f51ae6433c51    0    0    0    0   0    0 0.000000000    0    0    0    0    0    0    0    0   0    0    0    0    0    0    0    0 0.000000000    0
8c691144d0091ef9eed7a9675242e0e8    0    0    0    0   0    0 0.005835327    0    0    0    0    0    0    0    0   0    0    0    0    0    0    0    0 0.000000000    0
fe1249118078655daaae50ec71675bfc    0    0    0    0   0    0 0.000000000    0    0    0    0    0    0    0    0   0    0    0    0    0    0    0    0 0.000000000    0
b87b19ac7c95a095cae2f798e53aef4f    0    0    0    0   0    0 0.000000000    0    0    0    0    0    0    0    0   0    0    0    0    0    0    0    0 0.000000000    0

So, I am really puzzled at this point why is this happening? Just to clarify, I employ always a consistent workflow to generate input files for phyloseq using QIIME2, and only this particular object is creating the issue when using `psmelt` function.

Please get back to me if you have experienced similar issue, or you might know something I don't.

Deni

**Comment by mmclaren42** [comment] 2018-11-18 01:55
I don't understand the workings of `psmelt` enough to help with it directly, but perhaps this code for a `tidyverse` alternative will be helpful. By going step by step you can hopefully spot where the problem is happening (Particularly, watch out for issues during the two joins). As a side benefit, this function is much faster than `psmelt`.
```{r}
# library(tidyverse)
library(dplyr)
library(tidyr)

tidy_psmelt <- function(physeq) {
    # First, make sure taxa are rows
    if (taxa_are_rows(physeq)) {
        st <- otu_table(physeq) %>% t
    } else {
        st <- otu_table(physeq)
    }
    # Convert to a tibble in tidy form
    st <- st %>% 
        as("matrix") %>%
        tibble::as_tibble(rownames = "Sample") %>%
        gather("OTU", "Abundance", -Sample)
    # Get the sample data as a tibble
    sam <- sample_data(physeq) %>% 
        as("data.frame") %>% 
        tibble::as_tibble(rownames = "Sample")
    # Same for the tax table
    tax <- tax_table(physeq) %>%
        as("matrix") %>%
        tibble::as_tibble(rownames = "OTU")
    # Now join them all into one
    tb <- st %>%
        left_join(sam, by = "Sample") %>%
        left_join(tax, by = "OTU")
    tb
}
```

**Comment by DeniRibicic** [comment] 2018-11-20 08:59
@mmclaren42 `tidy_psmelt` works great! I have `df` that I wanted.
The only "problem" here is that it is not throwing any error, so I have no clue what is going on with the regular `psmelt` function.
What I have found out additionally, is when plotting directly with the `phyloseq` `plot_bar` function, I get an empty chart returned.
Could it be that some characters in the dataset are messing up intrinsic phyloseq properties? Would be nice to hear @joey711 opinion?

Deni

**Comment by mmclaren42** [comment] 2018-11-20 21:20
If you post a link to download your phyloseq object then we/Joey can run it to find the problem. Or you can run the code for `psmelt` line by line to see where it fails. Get the source code for the function from entering `psmelt` at the command line, and run it line by line (it's not much longer than my tidy version).

**Comment by joey711** [comment] 2019-02-17 20:45
@DeniRibicic would be very helpful to see the object that caused this problem (or hear your diagnosis of it if you already figured it out).

I will close this issue for now because it looks like you solved it, but please do share because I cannot otherwise reproduce this bug.

**Closed by joey711** 2019-02-17 20:45 UTC
