### ISSUE TITLE
data normalization by sample type 

### ISSUE THREAD

**Issue by gabuali** [joey711/phyloseq#468] opened 2015-04-24 14:14 UTC
Hi Joey,

first, love using phyloseq!
When plotting barplots where data is summarized by sample type, with the taxa/sample previously sum-normalized (0-1 scale) with sampleTransformCounts, the resulting barplot is not on a 0-1 scale and it's height represents the number of samples for that sample type (example attached).  I realize this is intended behavior but am wondering if it's possible (and not difficult) to renormalize abundances per sample type so that the bar plots are 0-1?  Does that make sense?

many thanks!

galeb

![barplot_sampletype_4joey](https://cloud.githubusercontent.com/assets/8404525/7320431/8450ee2e-ea6a-11e4-8def-8114721192c8.png)

**Comment by joey711** [comment] 2015-04-28 17:48
Yes, there should be a way to do this with some additional ggplot adjustments.

I suspect what will work for your purpose and still be simple would be to include a `position = "dodge"` argument in the `geom_bar` layer, and then `facet_wrap(~Phylum)`. In this case the color would be redundant, but maybe still useful. In the present case you're stacking the phyla, which does obfuscate meaning to some extent.

**Comment by joey711** [comment] 2015-04-28 18:42
p.s. if you provide a reproducible example of this plot (for instance using the `GlobalPatterns` dataset), then I'll respond with modified code that does what you're asking.

**Comment by gabuali** [comment] 2015-04-28 19:36
much appreciated!  Here is code and sample image:

```
library( phyloseq )

data( GlobalPatterns )

# subset GlobalPatterns
gp <- prune_taxa(
  names( sort( taxa_sums(GlobalPatterns), decreasing = T )[ 1:10 ] ),
  GlobalPatterns
)

# sum-normalize
gp.norm <- transform_sample_counts( gp, function(x) x/sum(x) )
colSums(otu_table(gp.norm)[, 1:5] )
# CL3     CC1     SV1 M31Fcsw M11Fcsw 
#   1       1       1       1       1

# generate stacked bar plot
plot_bar(gp.norm, fill = 'Phylum', x = 'SampleType') + 
  geom_bar( aes(color = Phylum, fill = Phylum ), stat = 'identity', position = 'stack')
```




![example4joey](https://cloud.githubusercontent.com/assets/8404525/7378486/9f4e26d4-edbb-11e4-8ddb-7bb81be1487d.png)

**Comment by CarlyRae** [comment] 2015-04-30 18:41
I am trying to make a similar figure. I would like for my stacked phyla to be merged together. I realize you lose information this why, but it is easier to display and explain when merged. 

I ran the same code above, but added in the tax_glom part below. 

data( GlobalPatterns )

# subset GlobalPatterns
gp <- prune_taxa(
  names( sort( taxa_sums(GlobalPatterns), decreasing = T )[ 1:10 ] ),
  GlobalPatterns
)

# sum-normalize
gp.norm <- transform_sample_counts( gp, function(x) x/sum(x) )
colSums(otu_table(gp.norm)[, 1:5] )
# CL3     CC1     SV1 M31Fcsw M11Fcsw 
#   1       1       1       1       1

#########  ADDED this ####
gp.norm <- tax_glom(gp.norm, "Phylum")


# generate stacked bar plot
plot_bar(gp.norm, fill = 'Phylum', x = 'SampleType') + 
  geom_bar( aes(color = Phylum, fill = Phylum ), stat = 'identity', position = 'stack')


Yet, it merges some of the phyla, but not all. Is there a way to merge all the OTUs at a certain taxonomic level to represent them in one stack of a bar plot


![rplot05](https://cloud.githubusercontent.com/assets/3433598/7419952/96b38780-ef46-11e4-8db1-0bfc30581cf5.jpeg)

Thanks,

Carly

**Comment by CarlyRae** [comment] 2015-05-04 18:07
I see that using merge_samples can remove the divisions between OTUs in the same phyla. So, just determining how to divide the abundance by the sample number is all that is left.

data( GlobalPatterns )

#subset
gp <- prune_taxa(
  names( sort( taxa_sums(GlobalPatterns), decreasing = T )[ 1:10 ] ),
  GlobalPatterns
)

#sum-normalize

gp.norm <- transform_sample_counts( gp, function(x) x/sum(x ))
colSums(otu_table(gp.norm)[, 1:5] )

#merge
gp.norm_m <- merge_samples(gp.norm, "SampleType")
sample_data(gp.norm_m)$SampleType <- factor(sample_names(gp.norm_m))

#taxa merge

gp.norm_m <- tax_glom(gp.norm_m, "Phylum")

#generate stacked bar plot

plot_bar(gp.norm_m, fill = 'Phylum', x = 'SampleType') + 
  geom_bar( aes(color = Phylum, fill = Phylum ), stat = 'identity', position = 'stack')

![rplot](https://cloud.githubusercontent.com/assets/3433598/7459009/e5d961fe-f266-11e4-8f5b-76da0c049fea.jpeg)

**Comment by CarlyRae** [comment] 2015-05-07 16:49
Not sure if this completely solves the original post, but finally the figure looks good to me.

data( GlobalPatterns )

#subset
gp <- prune_taxa(
  names( sort( taxa_sums(GlobalPatterns), decreasing = T )[ 1:10 ] ),
  GlobalPatterns
)

#sum-normalize

gp.norm <- transform_sample_counts( gp, function(x) x/sum(x ))
colSums(otu_table(gp.norm)[, 1:5] )

#merge
gp.norm_m <- merge_samples(gp.norm, "SampleType")
sample_data(gp.norm_m)$SampleType <- factor(sample_names(gp.norm_m))

#taxa merge

gp.norm_m <- tax_glom(gp.norm_m, "Phylum")

##Transform to percentage of total available
gp.norm_m = transform_sample_counts(gp.norm_m, function(x) 100 * x/sum(x))

#generate stacked bar plot

plot_bar(gp.norm_m, fill = 'Phylum', x = 'SampleType') + 
  geom_bar( aes(color = Phylum, fill = Phylum ), stat = 'identity', position = 'stack') +
            ylab("Relative abundance (% of total sequences)")

![rplot](https://cloud.githubusercontent.com/assets/3433598/7520793/581d24ba-f4b7-11e4-92e0-e1693ce8e4d1.jpeg)

**Comment by gabuali** [comment] 2015-05-07 16:51
Have not checked your code, but this is exactly what I'm going for.  Many thanks!

**Comment by bedemickan** [comment] 2015-08-20 00:12
Very good graph, I still haven't had success in adding std error bars to these stacked bar plots, looks like that would be the next step for publication right, can anyone add std error bars to relative abundance plots?

Thanks in advance, Bede

**Comment by joey711** [comment] 2016-04-07 21:45
@bedemickan I don't think it error bars are appropriate for stacked bar charts. 

Otherwise, it looks like this issue is resolved. Will close for now.

**Closed by joey711** 2016-04-07 21:45 UTC

**Comment by joey711** [comment] 2016-05-13 17:23
https://github.com/joey711/phyloseq/issues/442

faceting beats stacking in most situations, for a number of important quant data viz reasons.

**Comment by Hanhan0926** [comment] 2018-03-13 23:09
I have a simple question. How can I increase the spaces between bars? I tried geom_bar(width = 0.5), but it didn't work...

This is the code I used:
p <- plot_bar(d95Bac.S.LB2.norm.phy, x= "Depth.cmblf", fill = 'Phylum', title = "LB2")
p <- p + geom_bar(aes(fill = Phylum), stat = "identity", position = "stack", colour = "black", width = 0.5, show.legend = FALSE)
p <- p + ylab("Relative abundance (% of total sequences)")
p <- p + coord_flip() 
p <- p + xlim("30", "15", "7", "3.5", "1.25", "0.25", "-1")
p <- p + theme(text = element_text(size = 15)) + 
  theme(legend.position="right") + 
  theme(legend.justification = "top") +
  theme(legend.text=element_text(size = 10)) + 
  theme(plot.title = element_text(hjust = 0.5)) +theme_bw()
p <- p + guides(fill=guide_legend(ncol=2))
plot(p)
