### ISSUE TITLE
psmelt bug: calling reshape instead of reshape2

### ISSUE THREAD

**Issue by michberr** [joey711/phyloseq#440] opened 2015-03-07 21:42 UTC
Hi Joey,

I'm getting the following error when i run psmelt:
 Error in order(mdf$Abundance, decreasing = TRUE) : argument 1 is not a vector

I traced back through the function and the issue is in this line:
mdf = melt(as(otutab, "matrix"), value.name = "Abundance")

Melt is not correctly assigning Abundance to the value column. 
It looks like this is a known issue with the melt function calling the reshape package instead of reshape2
See: https://groups.google.com/forum/#!topic/manipulatr/scoTBPEtLwM

You could either explicitly rename that column or in the above link they offer the fix of:
reshape2::melt.data.frame()

-Michelle

PS I showed phyloseq to a labmate last week and they said it was magical :)

**Comment by joey711** [comment] 2015-03-08 21:27
Hi Michelle!

Thanks for the bug report, and likely fix! 

Bioconductor generally doesn't allow `package::` as namespace guidance within package functions, although this approach does work great in interactive sessions. `::`-level functions are already exposed by packages, so the normal namespace specification is possible. In this case, we need `melt.array` which is a not-exported, internal function of reshape2 package. This means that `reshape2:::melt.array` should work.

However, I have not been able to reproduce this bug myself, and that rather old google group post (2011) had Hadley jump in at the end and say that an update to ggplot2 would fix all this. The phyloseq package does not directly use the first `reshape` package as a dependency, and I'm not sure what (if any) dependended-on packages might use reshape (it's getting old!).

Can you post a reproducible example? For some reason your R session info showed in my email but not on this issue tracker page. It looks like you loaded "reshape" before everything else? Or at least it was first in your search path before everything else. I think BioC will let me use the `reshape2:::melt.array` protection for this, but first I'd like to know a little more about the bug. It might be just the special case where you have loaded `reshape` first and then loaded phyloseq/etc. 

Thanks for the kind words about phyloseq! Hope all is well! 

joey

**Comment by michberr** [comment] 2015-03-09 01:22
Hey Joey,

So this seems like an issue of reshape2 not properly masking functions from reshape.  When i got this bug the other day I had accidentally loaded reshape instead of reshape2. I then loaded reshape2 and it said that melt() was masked from reshape. Furthermore, reshape2 appears before reshape in the search path. However, when i run either melt or psmelt it does not change the 'value' name. 

phylum.99
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 18 taxa and 183 samples ]
sample_data() Sample Data:       [ 183 samples by 20 sample variables ]
tax_table()   Taxonomy Table:    [ 18 taxa by 6 taxonomic ranks ]

# Loading reshape first
library(reshape)
> phylum_long <- psmelt(phylum.99)
Error in order(mdf$Abundance, decreasing = TRUE) :  argument 1 is not a vector

# I've already loaded reshape, now loading reshape2
> library(reshape2)

Attaching package: ‘reshape2’
The following objects are masked from ‘package:reshape’: colsplit, melt, recast

> phylum_long<-psmelt(phylum.99)
Error in order(mdf$Abundance, decreasing = TRUE) : argument 1 is not a vector

# Trying basic melt function
phylum_long<-melt(otu_table(phylum.99), value.name="Abundance")
names(phy.long)
[1] "X1"    "X2"    "value"


Here is my session info:

R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] reshape2_1.4       RColorBrewer_1.0-5 reshape_0.8.5     
[4] scales_0.2.4       plyr_1.8.1         ggplot2_1.0.0     
[7] phyloseq_1.10.0   

loaded via a namespace (and not attached):
 [1] ade4_1.6-2              annotate_1.44.0        
 [3] AnnotationDbi_1.28.1    ape_3.2                
 [5] Biobase_2.26.0          BiocGenerics_0.12.1    
 [7] biom_0.3.12             Biostrings_2.34.1      
 [9] cluster_1.15.3          codetools_0.2-9        
[11] colorspace_1.2-4        data.table_1.9.2       
[13] DBI_0.2-7               DESeq2_1.4.5           
[15] digest_0.6.4            foreach_1.4.2          
[17] genefilter_1.46.1       geneplotter_1.42.0     
[19] GenomeInfoDb_1.0.2      GenomicRanges_1.16.4   
[21] grid_3.1.2              gtable_0.1.2           
[23] igraph_0.7.1            IRanges_1.22.10        
[25] iterators_1.0.7         labeling_0.2           
[27] lattice_0.20-29         locfit_1.5-9.1         
[29] MASS_7.3-35             Matrix_1.1-4           
[31] multtest_2.20.0         munsell_0.4.2          
[33] nlme_3.1-118            parallel_3.1.2         
[35] permute_0.8-3           proto_0.3-10           
[37] Rcpp_0.11.2             RcppArmadillo_0.4.400.0
[39] RJSONIO_1.3-0           RSQLite_0.11.4         
[41] S4Vectors_0.4.0         splines_3.1.2          
[43] stats4_3.1.2            stringr_0.6.2          
[45] survival_2.37-7         tools_3.1.2            
[47] vegan_2.0-10            XML_3.98-1.1           
[49] xtable_1.7-3            XVector_0.4.0          
[51] zlibbioc_1.10.0        

 this is my search()
 [1] ".GlobalEnv"        "package:reshape2"  "package:reshape"  
 [4] "package:phyloseq"  "tools:rstudio"     "package:stats"    
 [7] "package:graphics"  "package:grDevices" "package:utils"    
[10] "package:datasets"  "package:methods"   "Autoloads"        
[13] "package:base"

**Comment by naarkhoo** [comment] 2015-04-16 15:14
I confirm psmelt does not like "reshape" but "reshape2".

**Comment by joey711** [comment] 2015-06-18 17:30
This is now fixed in `1.13.3+`.
If you don't want to install the devel version (simply wait for the next BioC release), then @michberr 's `detach` workaround should also be fine. This is due to a name collision with the old, slow "reshape" package. phyloseq uses the faster "reshape2" package of the same author. They both contain a function called `melt`. This issue is now fixed, as phyloseq explicitly calls `reshape2::melt` in all instances.

Will close for now.

joey

**Closed by joey711** 2015-06-18 17:30 UTC
