### ISSUE TITLE
biom convert not working #716

### ISSUE THREAD

**Issue by ariverosw** [joey711/phyloseq#903] opened 2018-03-21 15:51 UTC
Hello,

I replied to ticket #716 but got no answers, I assume is because is closed. I'm having a similar issue and I'm running version 2.1.5. Is there anything I can do to fix this. Fortunately is not crushing for all samples, thought I can't tell specifically if it is a memory issue or not since there is no output addressing why the job was actually killed. I really appreciate the help.

Cheers,

Alejandro

**Comment by joey711** [comment] 2018-03-21 17:11
Before anyone could have a hope of answering your question/issue, please consider this:

https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

**Comment by ariverosw** [comment] 2018-03-21 17:16
Thanks for the reply Joey, but I think I missed to mention that I'm running this in a linux environment. I don't think the biom convert algorithm has anything to do with R. Actually I'm not even calling the R module in the job.
Hope someone has a good tip here.

**Comment by joey711** [comment] 2018-03-21 17:26
the question of relevance of your problem to this issue tracker aside...

https://stackoverflow.com/help/mcve

The fact of running in linux does not exempt you of the requirement to post a problem statement that is actually answerable by someone. There is so little documentation in your post that it is impossible for someone to help.

Also, this is clearly an issue for the biom-format (or QIIME2?) projects:

https://github.com/biocore/biom-format

(and a duplicate of the issue that you linked)

**Closed by joey711** 2018-03-21 17:26 UTC
